language: node_js
node_js:
  - 'node'
  - '8'

matrix:
  fast_finish: true
  allow_failures:
    - node_js: 'node'

os:
  - osx

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - node_modules

install: 'npm install'
script: 'npm test'
